### ISSUE TITLE
splitting things up a bit?

### ISSUE THREAD

**Issue by jasonswearingen** [huntercfreeman/BlazorStudio#65]
in trying to learn blazor, I'm toying with the idea of embedding a little script editor + evaluation in a game.  This brought your work to my attention, so just an idea, but could you consider how much effort it would be to modularize things a bit?   For example, the editor window being a separate nuget package that can be installed separate from the rest of the IDE you are building.

Thanks for reading :)

**Comment by huntercfreeman** [comment]
Hi,

What you say about making the Text Editor Blazor component a nuget package
is a great idea!

I will start now making the nuget package for the Text Editor.

I have a video series on my youtube channel where I have been re-writing
the Blazor Text Editor from scratch. Perhaps you'll find the series useful
while learning Blazor. You can find the playlist at the following link:
https://youtube.com/playlist?list=PLG4PTDe2qc0i0COivTxn_rjSN96Xq-_K1

What I'll do is: I can make the nuget package and showcase in the next
video for my playlist the process of making the nuget package. And most
importantly I'll in the same video make a new Blazor application and
reference the nuget package. Then write up a quick script editor and
evaluator.

I will make a note to myself to email you when I finish making the nuget
package.

If you have any questions about Blazor feel free to send me an email and
I'll get back to you when I can.

**Comment by jasonswearingen** [comment]
thank you I will look through the videos!

**Comment by huntercfreeman** [comment]
Hey,

I put up Version 1.0.0 of the BlazorTextEditor nuget package.

In this youtube video I go over setting up and using the nuget package.

https://www.youtube.com/watch?v=bDgU360ZBkI

**Comment by jasonswearingen** [comment]
Thanks Hunter, I'm still not at the point in my Blazor edu where I can look at this yet.... but really looking forward to it.
